# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gpu_rnorm <- function(n, seed, mu = 0, sigma = 1) {
    .Call(`_examplePkgCuda_gpu_rnorm`, n, seed, mu, sigma)
}

rcpp_hello_world <- function() {
    .Call(`_examplePkgCuda_rcpp_hello_world`)
}

rcpp_thrust_version <- function() {
    invisible(.Call(`_examplePkgCuda_rcpp_thrust_version`))
}

