# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

curand_rnorm <- function(n, seed, mu, sigma) {
    .Call(`_examplePkgCuda_curand_rnorm`, n, seed, mu, sigma)
}

rcpp_hello_world <- function() {
    .Call(`_examplePkgCuda_rcpp_hello_world`)
}

rcpp_sum <- function(v) {
    .Call(`_examplePkgCuda_rcpp_sum`, v)
}

